title: Kelvin Kong # your name (or website title) here
logo: "/images/kelvin_ga_rounded.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Kelvin is a seasoned Data Scientist who have contributed to various sectors including Manufacturing, Financial and Training
  (as a trainer). He designs systems, architects databases, builds machine learning / deep learning models,
  and implements analytics and enterprise search solutions on highly secured banking production systems. These systems serve to
  optimize product yield, increase team productivity and efficiency, reduces manual labor and ultimately tries to elimate human errors.
  <br><br>
  He strives to make the world a better place to live by giving back people the most important resource: Time.
  <br><br>
  <a href="https://www.linkedin.com/in/kelvinkong/">My LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-154707428-1 # your Google Analytics tracking ID here
