title: Kelvin Kong # your name (or website title) here
logo: "/images/kelvin_ga_rounded.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I strive to make the world a better place for humans to live in by leveraging technology.
  <br><br>
  <a href="https://www.linkedin.com/in/kelvinkong/">View My LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-154707428-1 # your Google Analytics tracking ID here
